[package]
name = "ex1_grpc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
protobuf = "3.2.0"
grpc = "0.8.3"
tls-api = "0.9.0"

[build-dependencies]
protoc-rust-grpc = "0.8.3"
